### ISSUE TITLE
Character Audio Bugs

### ISSUE THREAD

**Issue by SuperKirbylover** [Squishy6094/character-select-coop#11]
there's a few issues i noticed with character select audio. a bug i noticed is, depending on the level, CHAR_SOUND_LETS_A_GO is really quiet. i know on bob-omb battlefield it's quiet, but on whomp's fortress, it's not too bad.

some lines are played in the incorrect contexts it sounds like. for example:
- CHAR_SOUND_OOOF does not play upon being pushed by a bully, it instead plays CHAR_SOUND_EEUH
- Diving into a wall seems to play CHAR_SOUND_UH2(?) instead of CHAR_SOUND_UH

**Comment by FrijolesYQueso** [comment]
I've also noticed the issue with CHAR_SOUND_LETS_A_GO

**Comment by Squishy6094** [comment]
I believe a majority of issues relate to CoopDX itself and not CS sadly. I know Agent was trying to change how CHAR_SOUND_LETS_A_GO played so it would be more compatible with CS, and the incorrect context sound I believe is an issue with the HOOK_ON_CHARACTER_SOUND functionality and whatever CHAR_SOUND variable it returns.

**Comment by SuperKirbylover** [comment]
ough that sucks. hopefully at some point there could be a fix implemented, through CS or coopDX

**Comment by Squishy6094** [comment]
Closing this issue as it's been inactive for a while and it's been resolved that this is for the most part a CoopDX Issue
