### ISSUE TITLE
Character's voicelines don't cut off other voicelines

### ISSUE THREAD

**Issue by Joelybean** [Squishy6094/character-select-coop#15]
Character's voicelines don't cut off or stop playing when another voiceline from the same character starts.
This is an issue because characters usually bonk before walljumping (unless it was on the first frame) and this leads to bonking voicelines playing at the same time as a successful walljumping sound, instead of being cancelled.  This sounds wrong, because it makes it seem like the character had a bad reaction to a successful walljump.

**Comment by Squishy6094** [comment]
Tested this on the latest In-Dev just to double check, Audio Cutoff is working just fine and this issue doesn't arise, What version of Character Select might you be on? (Can be found in the description of the mod and the CS menu)

**Comment by Joelybean** [comment]
> Tested this on the latest In-Dev just to double check, Audio Cutoff is working just fine and this issue doesn't arise, What version of Character Select might you be on? (Can be found in the description of the mod and the CS menu)

It says v1.9.1, it might be an older version by accident because I merged my old version files with the new update files
Just checked and yep, it's an older version.  I see in the v1.10 changelog that the bug was indeed fixed.  Thank you!
