### ISSUE TITLE
Squid Sisters hide nametag

### ISSUE THREAD

**Issue by KiraYamato94** [Squishy6094/character-select-coop#2]
Hello, I don't know if this is the right place to ask but when using the Squid Sister char-select, the player who uses the model has all player's nametag hided, and also the rest of the players can't see that player's nametag. This doesn't happen with other models like Birdo or Toadette, so I think something is wrong inside the "callie_geo.bin" and "marie_geo.bin" file.

![imagen](https://github.com/Squishy6094/character-select-coop/assets/1362150/1ac0f3ad-2d2f-4404-b414-d75b2d37b5af)
![imagen](https://github.com/Squishy6094/character-select-coop/assets/1362150/09b3c028-cdbb-4b3c-a1a0-a02a8c31aaa6)

**Comment by Squishy6094** [comment]
Hi! This is a known issue with the Squid Sisters and Previously Yumi Models relating to Frijoles' method of removing torso tilting. This has been fixed for Yumi, and we're awaiting a new Squid Sisters release/patch for this to be fixed. Thank you for your concern!

**Comment by FrijolesYQueso** [comment]
Hey! I'm the skinpack creator! So yeah, it's an issue on how I fix the torso tilting like Squishy said. I'm hoping to be able to fix the issue + finishing updating their models sometime soon. Sorry for the issue.
