### ISSUE TITLE
character_edit() resets custom star icons

### ISSUE THREAD

**Issue by wibblus** [Squishy6094/character-select-coop#5]
if a CS character is setup to have a custom celebration star using `character_add_celebration_star()`, and then later a `character_edit()` is called using that same character, any custom star icon they had will be reset to the default (the `starIcon` field in the character table becomes `nil`)

In my tests with a custom character, the custom star icon works just fine, and resets upon a character_edit call with any number of arguments supplied.

**Comment by Squishy6094** [comment]
Hiii, we had a similar issue when working on Character Save Names that was since patched, but we seemed to have missed this >.<'
Was this only with the star icons, Or were the star models affected as well?

**Comment by wibblus** [comment]
only star icons, since they're tied to the characterTable instead of the model number

**Comment by Squishy6094** [comment]
> only star icons, since they're tied to the characterTable instead of the model number

Understood, will work on fixing inconsistencies tomorrow, thank you so much for bringing this to my attention >v<
