### ISSUE TITLE
Game freezes when i make a Room with char select 1.8

### ISSUE THREAD

**Issue by CMDSKIDD** [Squishy6094/character-select-coop#8]
So I was about to test char select 1.8 but the game freezed when I pressed create

**Comment by Squishy6094** [comment]
You may have installed the mod improperly (very possible you've overwritten file), another mod could have caused the crash (likely improper texture sizing), or coop simple failed on you which tends to happen. Character Select is heavily tested before each release and no one has experienced problems, let alone crashes. If you could provide more information I could help your further

**Comment by CMDSKIDD** [comment]
Idk maybe the game freezed bcuz i have 107 chars

**Comment by CMDSKIDD** [comment]
An also, I didn't overwrite the file

**Comment by Squishy6094** [comment]
> Idk maybe the game freezed bcuz i have 107 chars

Well do some testing I guess, I wouldn't be surprised if one of the packs you're using is crashing the game. If you haven't, try using character select without any packs and see how that goes.

**Comment by CMDSKIDD** [comment]
Thx, I removed some packs and the game did not freeze
